### ISSUE TITLE
行高根据内容调整

### ISSUE THREAD

**Issue by lz520520** [surely-vue/surely-table#173]
设置了autoHeight了，但单元格内容如果出现aaa\nbbb这样的换行，高度不会自动调整，这个属性是在哪种情况下才会生效呀
![image](https://github.com/surely-vue/surely-table/assets/30519218/64980ac2-d1f5-40bf-ae15-056a0c6acb78)

**Comment by tangjinzhou** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

不是不调整，是没换行吧，这个需要自行设置css属性  

改成 pre-line 
![image](https://github.com/surely-vue/surely-table/assets/6937879/57efecad-7136-43fd-aeaa-5fea3d3b3c43)

**Comment by lz520520** [comment]
ok，问题解决了，加了一个ellipsis也会影响自动行高
