### ISSUE TITLE
分辨率大时,列宽异常

### ISSUE THREAD

**Issue by hn7830626** [surely-vue/surely-table#176]
![1699240104419](https://github.com/surely-vue/surely-table/assets/42940041/bb4ee7c0-b66d-4df3-9a0a-971f77a9fce0)
第一列显示很宽(固定列),第一列已经设置了最大宽度maxWidth,请问如何调整

**Comment by tangjinzhou** [comment]
提供下复现示例吧，最少也有个代码示例

**Comment by hn7830626** [comment]
<template>
  <s-table
    :columns="columns"
    :scroll="{ y: 400 }"
    :row-selection="{}"
    :pagination="false"
    :data-source="[]"
  ></s-table> 
</template>

<script>
import { ref } from 'vue'

export default {
  components: {},
  setup(props, {}) {
    const columns = ref([
      {
        title: '序号',
        dataIndex: '#',
        width: 60,
        maxWidth: 100,
        align: 'center',
        sorter: false,
        resizable: true,
        fixed: true,
      },
      {
        resizable: 'true',
        showSorterTooltip: 'false',
        title: '辅助核算',
        width: 200,
      },
      {
        dataIndex: 'empty',
        resizable: 'true',
        showSorterTooltip: 'false',
        title: '是否允许为空',
        width: 200,
      },
    ])

    return {
      columns,
    }
  },
}
</script>
<style lang="less" scoped></style>

**Comment by hn7830626** [comment]
![1699320669942](https://github.com/surely-vue/surely-table/assets/42940041/2ee1d5cd-7e5d-4b1b-af5d-69fd6b9402f1)

经测试,浏览器缩放到90%就会出现(谷歌浏览器),若不绑定row-selection属性,就正常显示

**Comment by Tdota2** [comment]
> ![1699320669942](https://user-images.githubusercontent.com/42940041/280890689-2ee1d5cd-7e5d-4b1b-af5d-69fd6b9402f1.png)
> 
> 经测试,浏览器缩放到90%就会出现(谷歌浏览器),若不绑定row-selection属性,就正常显示

是这样的，是row-selection导致的，即使设置columnWidth也是没有用的，当把选择框单独设置一列，缩放分辨率会很明显。我选择重写了选择列来解决这个问题，这样能更灵活，更符合业务

**Comment by hn7830626** [comment]
> > ![1699320669942](https://user-images.githubusercontent.com/42940041/280890689-2ee1d5cd-7e5d-4b1b-af5d-69fd6b9402f1.png)
> > 经测试,浏览器缩放到90%就会出现(谷歌浏览器),若不绑定row-selection属性,就正常显示
> 
> 是这样的，是row-selection导致的，即使设置columnWidth也是没有用的，当把选择框单独设置一列，缩放分辨率会很明显。我选择重写了选择列来解决这个问题，这样能更灵活，更符合业务

现在业务嵌套的比较深,希望团队修复这个BUG

**Comment by tangjinzhou** [comment]
update to 4.2.1
