### ISSUE TITLE
表格中的input无法再进行键盘移动光标

### ISSUE THREAD

**Issue by Tdota2** [surely-vue/surely-table#177]
背景：
在Surely Table中自定义了一个input，进行输入时想通过键盘左右键移动输入光标，失效了。

新版本开启了**rangeSelection**，左右键变为了选择单元格

https://github.com/surely-vue/surely-table/assets/69885396/20254dcc-b3dd-4e66-8708-d49f1011d7f5

当我将rangeSelection设为false，关闭了单元格选择，左右键仍然无法移动输入光标

https://github.com/surely-vue/surely-table/assets/69885396/7e37c6ae-152a-47d3-9d8f-0c8b43c8b5f0

请问下，关闭rangeSelection后不能使用左右键，是bug还是我本地代码问题？

**Comment by tangjinzhou** [comment]
升级 4.2.0
