### ISSUE TITLE
列宽拖拽能抛出回调吗？

### ISSUE THREAD

**Issue by ttjimsen** [surely-vue/surely-table#178]
想存储用户表格的状态，列宽拖拽没有回调无法保存起来

**Comment by tangjinzhou** [comment]
有一个 onResizeColumn 事件

**Comment by ttjimsen** [comment]
好的谢谢，刚看到还有个问题请教下，
![image](https://github.com/surely-vue/surely-table/assets/31235202/976ce4cc-bbfa-4679-81b6-e8fa70ef1f90)
这个页码英文是受到prolayout的影响吗？
