### ISSUE TITLE
lykj vip：openeditor方法可同时开启多个编辑，希望有单选的方法，行编辑时有只选中一行的方法。单元格编辑时有只选中一个单元格的方法

### ISSUE THREAD

**Issue by web-ning** [surely-vue/surely-table#180]
是否可以提供属性可多选/单选切换，同时在openEditor开启单元格的编辑后能自动选中编辑中的单元格，两个问题：1.需要个只能单选的功能；2.需要在openeditor时不仅仅开启编辑也能自动选中单元
---------------------------------------
openeditor 可以同时打开多个的，自动选中这个不好搞，暴露个api出来手动调吧

**Comment by tangjinzhou** [comment]
用户点击或双击只能打开一个单元格，多个单元格是你自己调用 openEditor 传了一个数组（大于1）吧

**Comment by tangjinzhou** [comment]
第二个问题，如你只开启了一个单元格，是自动 focus 的
