### ISSUE TITLE
lykj vip：通用事件beforeEdit或afterEdit

### ISSUE THREAD

**Issue by web-ning** [surely-vue/surely-table#181]
开启编辑前的判断和结束编辑前的判断。比如beforeEdit或afterEdit，来判断是否阻止开启或关闭编辑

**Comment by tangjinzhou** [comment]
beforeEdit 用这个就可以吧
![image](https://github.com/surely-vue/surely-table/assets/6937879/67e408d3-9425-4d1c-85dc-0b58f6b49692)

afterEdit 用 valueSetter

**Comment by web-ning** [comment]
beforeEdit昨天那种方式是有问题的，
第一，通过插槽生成modelValue，样式跟默认样式不一致且不好处理customRender格式化；
第二，我需要在开启编辑前需要异步判断，类似valueSetter

**Comment by tangjinzhou** [comment]
update to  4.2.2
