### ISSUE TITLE
国际化不生效

### ISSUE THREAD

**Issue by ttjimsen** [surely-vue/surely-table#185]
![image](https://github.com/surely-vue/surely-table/assets/31235202/fe7bede6-0827-411a-9da7-ea4bb15ff39a)
正常全局配置
![image](https://github.com/surely-vue/surely-table/assets/31235202/b9bdde56-8909-4544-a0ad-1a8dde62cbed)

页码为转成中文

使用ant-design-vue
![image](https://github.com/surely-vue/surely-table/assets/31235202/78d8bb98-fc3d-4e4f-9131-14f07fd82cda)

**Comment by tangjinzhou** [comment]
语法不对吧  :locale="zhCN"

**Comment by ttjimsen** [comment]
> 语法不对吧 :locale="zhCN"

好吧 ^_^，谢谢
