### ISSUE TITLE
拖动改变列宽时，表格其他列的宽度小于设置的minWidth，而且表格的横向滚动条有时候出现有时候隐藏

### ISSUE THREAD

**Issue by winxiaoli** [surely-vue/surely-table#187]
重现步骤：
@surely-vue/table版本：4.2.2
部分列没有列宽且可以拖动改变宽度，最后一列没有列宽只有minWidth，拖动其他列改变列宽时，表格的横向滚动条有时候出现有时候隐藏，且最后一列的宽度会小于最小宽度
现象如下图
![飞书20231130-085907](https://github.com/surely-vue/surely-table/assets/52645122/085344df-cdb1-47c8-bfb4-827551506a80)
设置的最小列宽
![20231130-085854](https://github.com/surely-vue/surely-table/assets/52645122/7558ec8c-9071-4e90-bf58-eaf264f811ae)
实际列宽
![20231130-085900](https://github.com/surely-vue/surely-table/assets/52645122/3acc1fb2-01ac-4934-92f0-d20f8011f72e)

**Comment by winxiaoli** [comment]
新的代码示例，更容易复现了，之前的表头dataIndex重复了
[table-example.zip](https://github.com/surely-vue/surely-table/files/13508073/table-example.zip)

**Comment by tangjinzhou** [comment]
你的压缩包下载下来 .vue 打不开啊，神奇

**Comment by tangjinzhou** [comment]
你可以直接给个在线的不，直接在下面链接更改后回复我新的链接  https:codesandbox.io/s/surely-vue-demo-forked-k52qpj?file=/src/main.ts

**Comment by winxiaoli** [comment]
在线地址如下
https://codesandbox.io/p/devbox/surely-vue-demo-forked-4h84l5?file=%2Fsrc%2FApp.vue%3A13%2C12

**Comment by winxiaoli** [comment]
在线地址拖动列宽即可复现
![20231207110219_rec_](https://github.com/surely-vue/surely-table/assets/52645122/1f10805c-9440-4ac1-a9dc-e649e89eb01a)

**Comment by tangjinzhou** [comment]
建议你把 scroll.x 去掉，这个和拖拽组合起来就会出问题

**Comment by winxiaoli** [comment]
> 建议你把 scroll.x 去掉，这个和拖拽组合起来就会出问题

去掉了scroll，还是可以复现问题
