### ISSUE TITLE
请问customRender能否配置单元格的背景颜色

### ISSUE THREAD

**Issue by swansrp** [surely-vue/surely-table#189]
各位大佬好
我看官方文档写 customRender的作用是:
生成复杂数据的渲染函数，参数分别为当前行的值，当前行数据，行索引，@return 里面可以设置表格行/列合并,可参考 demo 表格行/列合并
我看咱们源码的话  customRender 返回的类型包含
    key?: Key;
    class?: string;
    style?: CSSProperties;
    colSpan?: number;
    rowSpan?: number;
我想知道这个style是否支持配置(我配置了backgroundColor不生效)

谢谢

**Comment by tangjinzhou** [comment]
https://www.surely.cool/doc/custom#bg-color  看一下这个  demo

**Comment by swansrp** [comment]
谢谢 我尝试一下 我感觉是customRender触发的条件我把握的不好 所以没有成功
谢谢您的指点
