### ISSUE TITLE
表格内容过少时 右键菜单显示不完整

### ISSUE THREAD

**Issue by swansrp** [surely-vue/surely-table#196]
示例 https://www.surely.cool/doc/basic#contextmenu
右键菜单
设置 contextmenuPopup 插槽，启用右键菜单功能，我们提供了足够多的参数供你自定义各种右键菜单项。
当表格内容设置成1条时
右键菜单显示不完整
右键菜单根据表格高度显示,当表格高度小于右键菜单时,显示出现异常

**Comment by tangjinzhou** [comment]
高度不够的时候应该出现了滚动条的吧？
或者可以给表格一个最小高度，
另外后续会提供弹出内容自定义

**Comment by swansrp** [comment]
谢谢 我采取给一个最小高度的方案 谢谢您的指点

**Comment by swansrp** [comment]
经测试 给表格最小高度的方案不生效 
surely-table-body-viewport-container
配置后表格可以撑开
但是右键弹出菜单还是被单独一行遮盖
关键样式:
overflow: hidden
去除该样式表格滚动失效
烦请作者关注

**Comment by tangjinzhou** [comment]
4.2.8

**Comment by swansrp** [comment]
4.2.8 fixed
thanks a lot
