### ISSUE TITLE
4.2.4 tooltip 控制台报错warning

### ISSUE THREAD

**Issue by swansrp** [surely-vue/surely-table#202]
更新4.2.4后
[Vue warn]: Invalid prop: type check failed for prop "popupStyle". Expected Object, got Boolean with value false. 
[Vue warn]: Invalid prop: type check failed for prop "overlayStyle". Expected Object, got Boolean with value false.
回退4.2.3后不出现
此外4.2.4 版本开始，支持了 tooltip 的 shouldOpen 属性，可以自定义是否开启 tooltip，也可以根据是否有省略号来判断是否显示。
>>也可以根据是否有省略号来判断是否显示。<< 
能否针对这个场景给个例子

**Comment by tangjinzhou** [comment]
4.2.5
