### ISSUE TITLE
columns配置项里添加自定义渲染每一列单元格内容的api

### ISSUE THREAD

**Issue by ljf1834** [surely-vue/surely-table#208]
多个表格共用同一个table实例时，使用自定义渲染内容slot-bodyCell插槽是非常痛苦的。需要在模板中编写多个v-if、v-else-if，如果直接再columns配置里可以配置渲染内容代码可读性将大大提高，也更符合开发者常规的开发思路。

**Comment by tangjinzhou** [comment]
customRender 返回 {children: xxx}

**Comment by ljf1834** [comment]
这个api目前是无效的，我尝试返回字符串和VNode都不生效

**Comment by ljf1834** [comment]
> 这个api目前是无效的，我尝试返回字符串和VNode都不生效

当前版本是4.2.8

**Comment by ljf1834** [comment]
> customRender 返回 {children: xxx}
同时使用customRender=>{children: xxx}和bodyCell插槽，bodyCell插槽的优先级比customRender高，导致customRender不生效。
