### ISSUE TITLE
【Bug】行拖拽的问题，会出现空白，官网可复现

### ISSUE THREAD

**Issue by qpxtWhite** [surely-vue/surely-table#214]
https://github.com/surely-vue/surely-table/assets/4169498/adc1081e-0df6-4a9b-9b8e-5c9d23f272ed

如视频所示，行拖拽时出现Bug，顶部一行空白
稳定复现逻辑：
1. Edrward1 挪到最上方
2. Edrward2 挪到最上方
3. Edrward0 挪到 1 和 2 中间
4. Edrward0 挪到最上方

**Comment by tangjinzhou** [comment]
update to 4.2.13
