### ISSUE TITLE
lykj-vip: 使用属性height后，右键菜单显示的位置有问题

### ISSUE THREAD

**Issue by web-ning** [surely-vue/surely-table#215]
使用属性height后，右键菜单显示的位置有问题：超过表格高度的行点击右键后，右键菜单top显示的是表格高度值
![image](https://github.com/surely-vue/surely-table/assets/43629659/4ce1314f-2a87-4158-9026-52a68490806b)
![image](https://github.com/surely-vue/surely-table/assets/43629659/97ac335b-42e1-4983-bad7-2bba39edcc7a)

**Comment by tangjinzhou** [comment]
update to 4.3.0
