### ISSUE TITLE
在单元格中放入输入框，输入中文时光标位置错误

### ISSUE THREAD

**Issue by Tdota2** [surely-vue/surely-table#217]
我在官网中的示例复现了这个现象，单元格中有输入框，在前面的某个位置输入中文，光标移动到了最后，且文字可能出现消失。‘
当我把鼠标移出单元格再进行输入，就输入正常了

错误现象如下
https://github.com/surely-vue/surely-table/assets/69885396/2c11df4b-25cf-4491-8e9b-37867168daa0

**Comment by tangjinzhou** [comment]
麻烦提供下更多的信息，操作系统，浏览器版本等，我这里没有复现

**Comment by Tdota2** [comment]
win11系统

Microsoft Edge
版本 122.0.2365.80 (正式版本) (64 位)

系统默认自带输入法

可随时在**官网-可编辑单元格**复现
https://www.surely.cool/doc/edit#edit-cell

**Comment by Tdota2** [comment]
> 麻烦提供下更多的信息，操作系统，浏览器版本等，我这里没有复现

win11系统

Microsoft Edge
版本 122.0.2365.80 (正式版本) (64 位)

系统默认自带输入法

可随时在官网-可编辑单元格复现
https://www.surely.cool/doc/edit#edit-cell

**Comment by wsxe9988** [comment]
> 这个是 antdv 那边的 bug ，可以先换成原生 input，或者使用 surely 自带的编辑功能
