### ISSUE TITLE
lykj-vip（加急）：使用分页组件切换页码后，再过滤数据，页码未随页面展示置回第一条

### ISSUE THREAD

**Issue by wzwzsos123** [surely-vue/surely-table#220]
网址：https://codesandbox.io/p/devbox/surely-vue-demo-forked-gl2pqv?file=%2Fsrc%2Fviews%2Fdemo.vue%3A117%2C29
实例：https://gl2pqv-5173.csb.app/demo

![image](https://github.com/surely-vue/surely-table/assets/39111980/bb5bff20-de5f-4f68-b4d9-389ae3557f32)

**Comment by wzwzsos123** [comment]
https://github.com/surely-vue/surely-table/assets/39111980/257d7699-c7ac-49e1-8845-0c57cfd344c6

**Comment by tangjinzhou** [comment]
没权限查看

**Comment by wzwzsos123** [comment]
> 没权限查看

已经开了

**Comment by tangjinzhou** [comment]
update to 4.3.1
