### ISSUE TITLE
4.3.3版本，rowHeight失效问题

### ISSUE THREAD

**Issue by Tdota2** [surely-vue/surely-table#227]
代码版本
"@surely-vue/table": "^4.3.3",
"ant-design-vue": "^4.1.2",
"vue": "^3.2.16"

demo地址：（可复现）
https://github.com/Tdota2/STable-test.git

demo现象：
最新版本中，同时设置rowHeight和column的autoHeight，rowHeight失效，会使用autoHeight属性，导致行高变小。之前的4.2.x版本中，会优先rowHeight属性。
是逻辑调整还是bug？

![image](https://github.com/surely-vue/surely-table/assets/69885396/cbae5297-8252-42d2-9784-0f240708950f)
![image](https://github.com/surely-vue/surely-table/assets/69885396/815d863a-dd73-4e47-afba-7852f7a067e9)
![image](https://github.com/surely-vue/surely-table/assets/69885396/219d6763-ff0b-482f-b5ce-38c01c3cf85e)

**Comment by tangjinzhou** [comment]
逻辑调整，如果是之前的逻辑， autoHeight 就没有存在的必要了

**Comment by Tdota2** [comment]
> autoHeight 就没有存在的必要了

好的，那我修改我的逻辑。因为功能使用之前的逻辑，对于同一个表格，为了优化部分客户的性能，使用rowHeight来固定行高，这样的话我修改为限制autoHeight。
