### ISSUE TITLE
表单数据未包含key字段或未设置rowKey为表格数据中的字段时显示异常

### ISSUE THREAD

**Issue by VENI-VIDIVICI** [surely-vue/surely-table#59]
复现链接：https://stackblitz.com/edit/vitejs-vite-z1eoxv?file=src/components/HelloWorld.vue

**Comment by tangjinzhou** [comment]
就是要指定 key 啊，这是规范

**Comment by VENI-VIDIVICI** [comment]
> 就是要指定 key 啊，这是规范

ant design vue 可正常使用

**Comment by tangjinzhou** [comment]
ant design vue 会自动生成一个随机key，但 surely涉及虚拟滚动，随机生成性能会影响性能，建议还是自行添加一个

**Comment by HYLLiving** [comment]
如何将key的键改为自定义？

**Comment by HYLLiving** [comment]
> 



> Reference in new issue



> 如何将key的键改为自定义？



> 如何将key的键改为自定义？

在文档找到了，api那一栏，使用rowKey重新指定key的键
